checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php:
      version: 7.1
  tests:
    override:
      - command: vendor/bin/codecept run unit --coverage-xml=build/clover.xml
        coverage:
          file: tests/_output/build/clover.xml
          format: clover

filter:
  excluded_paths:
    - "./tests"
