language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer --prefer-dist install